/**
 * 航天器机库目录 VehicleCatalog
 * 遵循 04-VEHICLES.zh-CN.md：真实历史参数、米制尺寸、结构热点与亲子记忆点
 */

import type { VehicleDefinition, VehicleId } from '../contracts/vehicle';

export const VEHICLE_CATALOG: Record<VehicleId, VehicleDefinition> = {
  'juno': {
    id:'juno',name:'朱诺号',nameEn:'Juno',type:'orbiter',era:'contemporary',agency:'NASA / JPL',launchYear:2011,
    dimensions:{lengthM:20,widthM:20,heightM:4.5},dimensionsNote:'太阳翼展开直径约20米；参考资料尺寸，不是模型测量标尺。',massKg:3625,
    kidFact:'三片巨大的太阳翼，帮助这位木星侦探研究云层下面藏着什么。',
    description:'朱诺号于2011年发射，2016年进入木星轨道。它通过重力、磁场和微波观测研究木星内部与大气，并拍摄极区云带。',
    keyMilestone:'首个在木星执行轨道任务的太阳能航天器。',hotspots:[],accentColorHex:0xc9a764,
    sourceRef:'https://www.jpl.nasa.gov/news/press_kits/juno/facts/',
  },
  'space-shuttle': {
    id:'space-shuttle',name:'航天飞机',nameEn:'Space Shuttle Orbiter',type:'crewed-orbiter',era:'classic',agency:'NASA',launchYear:1981,
    dimensions:{lengthM:37.24,widthM:23.79,heightM:17.25},dimensionsNote:'轨道器参考尺寸（高度按跑道构型）；模型展示在轨构型。',
    kidFact:'像火箭一样升空，在太空工作后，像滑翔机一样回到跑道。',
    description:'美国航天飞机承担载人飞行、卫星部署和维修、空间科学实验与空间站建设。这里展示轨道器本体，含货舱门、尾部三台主发动机与轨道机动发动机。',
    keyMilestone:'参与哈勃太空望远镜的部署与维修，以及国际空间站建设。',hotspots:[],accentColorHex:0xdce5ef,
    sourceRef:'https://ntrs.nasa.gov/api/citations/19940023701/downloads/19940023701.pdf',
  },
  'apollo-lm': {
    id: 'apollo-lm',
    name: '阿波罗登月舱',
    nameEn: 'Apollo 11 Lunar Module (Eagle)',
    type: 'crewed-lander',
    era: 'classic',
    agency: 'NASA',
    launchYear: 1969,
    dimensions: {
      lengthM: 9.4,
      widthM: 9.4,
      heightM: 7.04,
    },
    massKg: 15200,
    kidFact: '就是这艘像大蜘蛛一样的飞船，把人类宇航员第一次送上了月球表面！',
    description: '1969 年 7 月 20 日，阿波罗 11 号“鹰号”登月舱成功着陆月球静海。它分为下部着陆级（留有四条着陆支架和金箔隔热层）和上部上升级（宇航员座舱，任务结束后点火飞离月面与指令舱对接）。',
    keyMilestone: '1969 年阿姆斯特朗踏上月球：“这是我个人的一小步，却是人类的一大步。”',
    hotspots: [
      {
        id: 'ascent-stage',
        name: '上升级座舱',
        relativePosM: [0, 2.2, 0],
        kidTip: '宇航员叔叔就是站在这个带有两扇三角形小窗户的紧凑舱室里驾驶飞船的！',
        scienceDetail: '上升级包含乘员舱、环境控制系统、反应控制姿态喷管以及起飞推进发动机。',
      },
      {
        id: 'gold-mylar',
        name: '金箔隔热层',
        relativePosM: [0, 0.8, 0],
        kidTip: '金灿灿的衣服不是金子做的，而是高科技反光隔热膜，防止太空极度严寒或暴晒！',
        scienceDetail: '由镀铝聚酰亚胺薄膜（Kapton/Mylar）层叠组成的多层隔热层（MLI），用于抵御无大气环境下的极端辐射热。',
      },
      {
        id: 'landing-gear',
        name: '四足着陆支架',
        relativePosM: [0, -1.8, 0],
        kidTip: '四条大脚爪内部装有蜂窝铝缓冲吸能材料，让登月舱稳稳停在松软的月尘上。',
        scienceDetail: '可折叠桁架式着陆支脚，展开跨度达 9.4 米，其中一个支脚装有登月扶梯与登月纪念牌。',
      },
    ],
    accentColorHex: 0xd4af37, // 金箔色
    sourceRef: 'NASA Apollo 11 Lunar Module Documentation',
  },
  'voyager-1': {
    id: 'voyager-1',
    name: '旅行者 1 号',
    nameEn: 'Voyager 1',
    type: 'interstellar',
    era: 'classic',
    agency: 'NASA / JPL',
    launchYear: 1977,
    dimensions: {
      lengthM: 3.7,
      widthM: 3.7,
      heightM: 2.5,
    },
    massKg: 825,
    kidFact: '它是人类制造的飞得最远的使者，现在已经飞出了太阳系，带着一张镀金唱片奔向星辰大海！',
    description: '1977 年发射，利用罕见的行星引力弹弓效应飞掠木星与土星，拍摄了大量震撼人类的近距特写。2012 年正式穿过日球层顶进入星际空间，距离地球已超 240 亿公里。',
    keyMilestone: '飞掠木星发现木卫一活火山；拍摄著名的“暗淡蓝点”（Pale Blue Dot）地球照片。',
    hotspots: [
      {
        id: 'dish-antenna',
        name: '高增益天线大锅',
        relativePosM: [0, 1.2, 0],
        kidTip: '直径 3.7 米的巨大白色天线像一把大伞，哪怕隔着 200 多亿公里，依然向地球发回微弱信号！',
        scienceDetail: 'X 波段与 S 波段抛物面高增益天线（HGA），负责在数十天文单位外与地球深空测控网（DSN）保持通信。',
      },
      {
        id: 'golden-record',
        name: '旅行者金唱片',
        relativePosM: [0.8, 0, 0],
        kidTip: '唱片里录着地球上的风声、雨声、鸟叫、摇篮曲和 55 种人类语言的问候，给可能遇到的外星朋友！',
        scienceDetail: '镀金铜制 12 英寸音像光盘，表面刻有太阳系位置脉冲星地图与播放示意图，寿命可达数十亿年。',
      },
      {
        id: 'rtg-power',
        name: '放射性同位素热电机 (RTG)',
        relativePosM: [-1.8, -0.5, 0],
        kidTip: '外层空间太阳光太微弱，它靠核电池自然衰变产生的热量持续发电近半个世纪！',
        scienceDetail: '三座钚-238 放射性同位素温差热电机，安装在伸出长臂上，远离科学仪器以避免辐射干扰。',
      },
    ],
    accentColorHex: 0xf59e0b,
    sourceRef: 'NASA JPL Voyager Interstellar Mission',
  },
  'james-webb': {
    id: 'james-webb',
    name: '詹姆斯·韦伯太空望远镜',
    nameEn: 'James Webb Space Telescope (JWST)',
    type: 'space-telescope',
    era: 'contemporary',
    agency: 'NASA / ESA / CSA',
    launchYear: 2021,
    dimensions: {
      lengthM: 20.2,
      widthM: 14.2,
      heightM: 8.0,
    },
    massKg: 6500,
    kidFact: '它有一面金灿灿的 18 块六边形超级黄金大魔镜，能看透深空宇宙 135 亿年前的第一缕微光！',
    description: '人类有史以来建造的最强红外太空望远镜，运行在距离地球 150 万公里的拉格朗日 L2 点。通过超大遮阳板遮挡太阳和地球的热辐射，将主镜冷却至零下 233°C 以下，探索早期宇宙星系与系外行星大气。',
    keyMilestone: '拍摄首批深空全彩宇宙图像；直接观测到宇宙诞生数亿年内的最古老星系。',
    hotspots: [
      {
        id: 'primary-mirror',
        name: '18 块镀金六边形主镜',
        relativePosM: [0, 1.8, 0],
        kidTip: '由超轻的金属铍制成，表面镀着比头发丝还薄 100 倍的真金，因为黄金反射红外线最强！',
        scienceDetail: '总有效口径 6.5 米，由 18 个独立的六边形子镜拼成，每个子镜背面有微米级压电致动器精确校准光轴。',
      },
      {
        id: 'sunshield',
        name: '五层风筝遮阳薄膜',
        relativePosM: [0, -1.2, 0],
        kidTip: '足足有一个网球场那么大！五层银色风筝层层散热，向阳面能煎鸡蛋，背阴面冷到接近绝对零度！',
        scienceDetail: '采用五层经过铝和掺杂硅涂层处理的聚酰亚胺薄膜（Kapton），层间真空隔离，温差高达 300°C。',
      },
    ],
    accentColorHex: 0xeab308,
    sourceRef: 'NASA / STScI James Webb Space Telescope',
  },
  'hubble': {
    id: 'hubble',
    name: '哈勃太空望远镜',
    nameEn: 'Hubble Space Telescope (HST)',
    type: 'space-telescope',
    era: 'contemporary',
    agency: 'NASA / ESA',
    launchYear: 1990,
    dimensions: {
      lengthM: 13.2,
      widthM: 4.2,
      heightM: 4.2,
    },
    massKg: 11110,
    kidFact: '宇宙中不知疲倦的大眼睛！它在太空中给几千亿光年外的星云和星系拍下了最清晰的彩色肖像！',
    description: '1990 年 4 月由发现号航天飞机送入距地球约 540 公里的近地低轨道。作为人类历史上最伟大的光学太空望远镜，它避开了地球稠密大气的扰动与光污染，彻底改变了人类对宇宙年龄、暗能量及星系演化的认知。',
    keyMilestone: '拍摄著名的哈勃深空场（Hubble Deep Field）与“创生之柱”；精确测定宇宙膨胀速度。',
    hotspots: [
      {
        id: 'primary-mirror',
        name: '2.4 米超高精度主镜',
        relativePosM: [0, 1.2, 0],
        kidTip: '主镜就像一块巨大的银色聚光盘，表面光滑得如果有一块大陆那么大，最大的颠簸也不超过几厘米！',
        scienceDetail: '有效口径 2.4 米的双曲面反射镜，采用康宁超低膨胀玻璃制成，表面镀有超纯铝和氟化镁反射涂层。',
      },
      {
        id: 'solar-arrays',
        name: '双翼柔性太阳翼',
        relativePosM: [3.8, 0, 0],
        kidTip: '左右两面宽大的太阳翼像翅膀一样张开，随着望远镜绕地球飞行自动转动追踪阳光提供电能。',
        scienceDetail: '由欧洲空间局研制的柔性硅光伏电池阵列，经历多次航天飞机太空维护升级，输出稳定充沛的直流电。',
      },
      {
        id: 'aperture-door',
        name: '活动遮光保护门',
        relativePosM: [0, 4.8, 0],
        kidTip: '镜筒顶部的翻盖小门！在火箭发射时关得紧紧的，进入太空后才缓缓打开，防止任何杂散光或太阳强光直射！',
        scienceDetail: '电动可开闭式镜筒前端遮光挡板，当望远镜指向接近太阳方向时会自动迅速闭合以保护精密感光元件。',
      },
      {
        id: 'wfc3-camera',
        name: '第三代广角行星相机 (WFC3)',
        relativePosM: [0, -3.2, 0],
        kidTip: '望远镜的心脏照相机！宇航员叔叔曾专门坐航天飞机上天给它换上这个最新的超级数码相机！',
        scienceDetail: '安装在望远镜轴向仪器舱，覆盖从近紫外、可见光到近红外的超宽光谱波段，成像锐度极高。',
      },
    ],
    accentColorHex: 0x94a3b8, // 钛银与多层隔热被色
    sourceRef: 'NASA / STScI Hubble Space Telescope Official Data',
    isFeatured: true,
    modelFormat: 'glb',
    modelAssetPath: '/assets/models/hubble-nasa-b.glb',
    modelSourceUrl: 'https://science.nasa.gov/3d-resources/hubble-space-telescope-b/',
    modelLicense: 'NASA Open Data / Public Domain',
    modelApproved: true,
  },
  'iss': {
    id: 'iss',
    name: '国际空间站',
    nameEn: 'International Space Station (ISS)',
    type: 'space-station',
    era: 'contemporary',
    agency: 'NASA / Roscosmos / ESA / JAXA / CSA',
    launchYear: 1998,
    dimensions: {
      lengthM: 109.0,
      widthM: 73.0,
      heightM: 20.0,
    },
    massKg: 450000,
    kidFact: '人类在太空搭建的最大城堡，面积比一个足球场还大，航天员叔叔阿姨在上面每天看 16 次日出！',
    description: '在距地球约 400 公里的近地轨道上以每秒 7.7 公里的速度绕地飞行，每 90 分钟绕地球一圈。拥有宽大的太阳能电池翼和多个国家的科研舱段，人类已连续在轨驻留超过 24 年。',
    keyMilestone: '人类在轨最久的大型微重力多学科国际太空实验室。',
    hotspots: [
      {
        id: 'solar-arrays',
        name: '巨大太阳能电池翼',
        relativePosM: [0, 0, 0],
        kidTip: '展开后长达上百米，像大翅膀一样自动转动追踪太阳，为整个空间站提供源源不断的电能。',
        scienceDetail: '总面积达 2400 平方米，可输出高达 120 千瓦电功率。',
      },
      {
        id: 'cupola',
        name: '穹顶观测舱 (Cupola)',
        relativePosM: [0, -1.5, 2.0],
        kidTip: '空间站上的大天窗！拥有 7 扇坚固的防辐射观察窗，宇航员在这里俯瞰美丽的蓝色地球。',
        scienceDetail: '由欧洲空间局建造，是空间站机器人遥控操作与地球光学观测的最佳视窗。',
      },
    ],
    accentColorHex: 0x38bdf8,
    sourceRef: 'NASA International Space Station Facts and Figures',
    isFeatured: true,
    modelFormat: 'procedural',
    modelApproved: true,
  },
  'tiangong': {
    id: 'tiangong',
    name: '中国天宫空间站',
    nameEn: 'Tiangong Space Station',
    type: 'space-station',
    era: 'contemporary',
    agency: 'CNSA 中国国家航天局',
    launchYear: 2021,
    dimensions: {
      lengthM: 37.0,
      widthM: 33.0,
      heightM: 10.0,
    },
    massKg: 100000,
    kidFact: '中国自主建造的现代化太空家园，由天和核心舱、问天实验舱和梦天实验舱组成优雅的“T”字形！',
    description: '中国国家太空实验室，运行在 400 公里近地倾斜轨道。配备柔性三结砷化镓双自由度太阳翼、高智能七自由度机械臂，支持 3 名航天员长期驻留及乘组轮换。',
    keyMilestone: '中国空间站全面建成进入应用与发展新阶段，开展前沿太空微重力科学实验。',
    hotspots: [
      {
        id: 'tianhe-core',
        name: '天和核心舱',
        relativePosM: [0, 0, 0],
        kidTip: '空间站的“大脑”和宇航员起居室，有舒适的独立卧室、卫生间、健身房和太空厨房！',
        scienceDetail: '全长 16.6 米，最大直径 4.2 米，负责空间站组合体统一管理控制、航天员生活起居与出舱活动。',
      },
      {
        id: 'flexible-solar',
        name: '柔性砷化镓双轴太阳翼',
        relativePosM: [15, 0, 0],
        kidTip: '像两幅薄薄的金色画卷一样在太空中缓缓展开，光电转换效率超过 30%！',
        scienceDetail: '三结砷化镓柔性太阳电池阵，采用双自由度对日定向驱动机构，即使在复杂姿态下也能获得最大光照。',
      },
      {
        id: 'robotic-arm',
        name: '大机械臂',
        relativePosM: [0, 2.0, 0],
        kidTip: '就像宇航员在太空中的大力士手臂，能在空间站表面像尺蠖一样一步步爬行！',
        scienceDetail: '七自由度空间机械臂，展开长达 10.2 米，最大承载能力达 25 吨，可协助实验舱转位与航天员出舱。',
      },
    ],
    accentColorHex: 0xef4444, // 中国红与航天金
    sourceRef: 'CMSA 中国载人航天工程网官方数据',
  },
  'cassini': {
    id: 'cassini',
    name: '卡西尼-惠更斯号',
    nameEn: 'Cassini-Huygens',
    type: 'orbiter',
    era: 'classic',
    agency: 'NASA / ESA / ASI',
    launchYear: 1997,
    dimensions: {
      lengthM: 6.7,
      widthM: 4.0,
      heightM: 4.0,
    },
    massKg: 5712,
    kidFact: '土星最忠实的侦探！环绕土星探索了 13 年，发现了土卫二南极的冰喷泉和土卫六的液态湖！',
    description: '人类建造的最宏大、最复杂的行星际探测器之一。搭载欧洲惠更斯号成功着陆土卫六泰坦星表面。在任务终章“大结局”中，卡西尼号主动纵身冲入土星大气层焚毁，保护可能拥有生命的卫星免受地球微生物污染。',
    keyMilestone: '发现土卫二冰下海洋与热液活动；22 次近距离穿越土星与光环之间的缝隙。',
    hotspots: [
      {
        id: 'high-gain-dish',
        name: '4 米碳纤维高增益天线',
        relativePosM: [0, 2.5, 0],
        kidTip: '不仅是通信大天线，在飞越土星光环时它还被转过来充当盾牌，抵挡微小碎冰尘埃的撞击！',
        scienceDetail: '直径 4 米的高精度双频抛物面反射天线，由意大利航天局研制，同时兼作雷达测绘天线与微流星防护罩。',
      },
      {
        id: 'huygens-probe',
        name: '惠更斯号泰坦着陆器',
        relativePosM: [1.8, 0, 0],
        kidTip: '像一个金色的圆盘飞碟，带着降落伞穿越了土卫六厚厚的橙色大雾，成功降落在外星球的冰石滩上！',
        scienceDetail: '重 318 千克的独立大气探测器，2005 年 1 月 14 日成功在土卫六软着陆，传回人类第一张外太阳系卫星地表实景照片。',
      },
    ],
    accentColorHex: 0x8b5cf6,
    sourceRef: 'NASA / JPL Cassini-Huygens Mission Documentation',
  },
};
